# "restricted" status is used for conjured/specialized cards, which is technically not a B&R issue

BanList.for_format("alchemy") do
  # HBG conjured/specialized
  change(
    "2022-07-07",
    nil,
    # Specialized cards
    "Alora, Cheerful Assassin" => "restricted",
    "Alora, Cheerful Mastermind" => "restricted",
    "Alora, Cheerful Scout" => "restricted",
    "Alora, Cheerful Swashbuckler" => "restricted",
    "Alora, Cheerful Thief" => "restricted",
    "Ambergris, Agent of Balance" => "restricted",
    "Ambergris, Agent of Destruction" => "restricted",
    "Ambergris, Agent of Law" => "restricted",
    "Ambergris, Agent of Progress" => "restricted",
    "Ambergris, Agent of Tyranny" => "restricted",
    "Gale, Abyssal Conduit" => "restricted",
    "Gale, Holy Conduit" => "restricted",
    "Gale, Primeval Conduit" => "restricted",
    "Gale, Storm Conduit" => "restricted",
    "Gale, Temporal Conduit" => "restricted",
    "Gut, Bestial Fanatic" => "restricted",
    "Gut, Brutal Fanatic" => "restricted",
    "Gut, Devious Fanatic" => "restricted",
    "Gut, Furious Fanatic" => "restricted",
    "Gut, Zealous Fanatic" => "restricted",
    "Imoen, Chaotic Trickster" => "restricted",
    "Imoen, Honorable Trickster" => "restricted",
    "Imoen, Occult Trickster" => "restricted",
    "Imoen, Wily Trickster" => "restricted",
    "Imoen, Wise Trickster" => "restricted",
    "Jaheira, Heroic Harper" => "restricted",
    "Jaheira, Insightful Harper" => "restricted",
    "Jaheira, Merciful Harper" => "restricted",
    "Jaheira, Ruthless Harper" => "restricted",
    "Jaheira, Stirring Harper" => "restricted",
    "Karlach, Tiefling Berserker" => "restricted",
    "Karlach, Tiefling Guardian" => "restricted",
    "Karlach, Tiefling Punisher" => "restricted",
    "Karlach, Tiefling Spellrager" => "restricted",
    "Karlach, Tiefling Zealot" => "restricted",
    "Klement, Death Acolyte" => "restricted",
    "Klement, Knowledge Acolyte" => "restricted",
    "Klement, Life Acolyte" => "restricted",
    "Klement, Nature Acolyte" => "restricted",
    "Klement, Tempest Acolyte" => "restricted",
    "Lae'zel, Blessed Warrior" => "restricted",
    "Lae'zel, Callous Warrior" => "restricted",
    "Lae'zel, Illithid Thrall" => "restricted",
    "Lae'zel, Primal Warrior" => "restricted",
    "Lae'zel, Wrathful Warrior" => "restricted",
    "Lukamina, Bear Form" => "restricted",
    "Lukamina, Crocodile Form" => "restricted",
    "Lukamina, Hawk Form" => "restricted",
    "Lukamina, Scorpion Form" => "restricted",
    "Lukamina, Wolf Form" => "restricted",
    "Lulu, Curious Hollyphant" => "restricted",
    "Lulu, Helpful Hollyphant" => "restricted",
    "Lulu, Inspiring Hollyphant" => "restricted",
    "Lulu, Vengeful Hollyphant" => "restricted",
    "Lulu, Wild Hollyphant" => "restricted",
    "Rasaad, Dragon Monk" => "restricted",
    "Rasaad, Radiant Monk" => "restricted",
    "Rasaad, Shadow Monk" => "restricted",
    "Rasaad, Sylvan Monk" => "restricted",
    "Rasaad, Warrior Monk" => "restricted",
    "Sarevok, Deadly Usurper" => "restricted",
    "Sarevok, Deceitful Usurper" => "restricted",
    "Sarevok, Divine Usurper" => "restricted",
    "Sarevok, Ferocious Usurper" => "restricted",
    "Sarevok, Mighty Usurper" => "restricted",
    "Shadowheart, Cleric of Graves" => "restricted",
    "Shadowheart, Cleric of Order" => "restricted",
    "Shadowheart, Cleric of Trickery" => "restricted",
    "Shadowheart, Cleric of Twilight" => "restricted",
    "Shadowheart, Cleric of War" => "restricted",
    "Skanos, Black Dragon Vassal" => "restricted",
    "Skanos, Blue Dragon Vassal" => "restricted",
    "Skanos, Green Dragon Vassal" => "restricted",
    "Skanos, Red Dragon Vassal" => "restricted",
    "Skanos, White Dragon Vassal" => "restricted",
    "Vhal, Scholar of Creation" => "restricted",
    "Vhal, Scholar of Elements" => "restricted",
    "Vhal, Scholar of Mortality" => "restricted",
    "Vhal, Scholar of Prophecy" => "restricted",
    "Vhal, Scholar of Tactics" => "restricted",
    "Viconia, Disciple of Arcana" => "restricted",
    "Viconia, Disciple of Blood" => "restricted",
    "Viconia, Disciple of Rebirth" => "restricted",
    "Viconia, Disciple of Strength" => "restricted",
    "Viconia, Disciple of Violence" => "restricted",
    "Wilson, Ardent Bear" => "restricted",
    "Wilson, Fearsome Bear" => "restricted",
    "Wilson, Majestic Bear" => "restricted",
    "Wilson, Subtle Bear" => "restricted",
    "Wilson, Urbane Bear" => "restricted",
    "Wyll of the Blade Pact" => "restricted",
    "Wyll of the Celestial Pact" => "restricted",
    "Wyll of the Elder Pact" => "restricted",
    "Wyll of the Fey Pact" => "restricted",
    "Wyll of the Fiend Pact" => "restricted",
    # conjure only cards
    "Hag of Ceaseless Torment" => "restricted",
    "Hag of Dark Duress" => "restricted",
    "Hag of Death's Legion" => "restricted",
    "Hag of Inner Weakness" => "restricted",
    "Hag of Mage's Doom" => "restricted",
    "Hag of Noxious Nightmares" => "restricted",
    "Hag of Scoured Thoughts" => "restricted",
    "Hag of Syphoned Breath" => "restricted",
    "Hag of Twisted Visions" => "restricted",
    # Now this is fun, HBG cards 900+ are conjure only, but some of these have other historic legal printings
    # It would be better to move these to a separete set
    "Archipelagore" => "restricted",
    "Junk Winder" => "restricted",
    "Moat Piranhas" => "restricted",
    "Mystic Skyfish" => "restricted",
    "Nadir Kraken" => "restricted",
    "Nezahal, Primal Tide" => "restricted",
    "Pouncing Shoreshark" => "restricted",
    "Pursued Whale" => "restricted",
    "Riptide Turtle" => "restricted",
    "Ruin Crab" => "restricted",
    "Sea-Dasher Octopus" => "restricted",
    "Sigiled Starfish" => "restricted",
    "Spined Megalodon" => "restricted",
    "Stinging Lionfish" => "restricted",
    "Voracious Greatshark" => "restricted",
    "Lightning Bolt" => "restricted",
    "Naturalize" => "restricted",
    # "Plummet" => "restricted", # also in MID (rotates with HBG)
  )

  # YDMU - it would be better to move these to a separete set
  change(
    "2022-10-05",
    nil,
    # conjure only cards
    "Ancestral Recall" => "restricted",
    "Time Walk" => "restricted",
    "Timetwister" => "restricted",
    "Black Lotus" => "restricted",
    "Mox Emerald" => "restricted",
    "Mox Jet" => "restricted",
    "Mox Pearl" => "restricted",
    "Mox Ruby" => "restricted",
    "Mox Sapphire" => "restricted",
  )

  change(
    "2023-07-18",
    "https://magic.wizards.com/en/news/mtg-arena/alchemy-rebalancing-for-july-18-2023",
    "Fable of the Mirror-Breaker" => "banned",
  )
end
