BanList.for_format("competitive brawl") do
  # The format launched with this list and has not changed since, and everything on it
  # was already true on day one, so it's all one undated block.
  #
  # The ten bans are not Brawl's list plus or minus anything - Competitive Brawl bans
  # commanders only, and starts from "almost every card being legal to include in the
  # 99", so everything Brawl bans in the 99 is legal here. Nadu is the rebalanced
  # version, as everything in Brawl is; "Brawl: Our Plans" spells it "A-Nadu, Winged
  # Wisdom" where the launch article just says "Nadu, Winged Wisdom".
  #
  # The rest is the conjure-only list, which is not a B&R issue at all - those cards
  # can't go into a deck in any Arena format. Format::RESTRICTED_STATUSES groups them
  # with the other restricted-family statuses for restricted: and f: searches. It's
  # Historic's list minus Lightning Bolt, which Historic only files as conjurable
  # because it's pre-banned there anyway.
  format_start(
    "https://magic.wizards.com/en/news/mtg-arena/introducing-ranked-brawl",
    "Ajani, Nacatl Pariah" => "banned",
    "Lutri, the Spellchaser" => "banned",
    "Nadu, Winged Wisdom (Alchemy)" => "banned",
    "Oko, Thief of Crowns" => "banned",
    "Old Stickfingers" => "banned",
    "Ragavan, Nimble Pilferer" => "banned",
    "Rusko, Clockmaker" => "banned",
    "Tajic, Legion's Valor" => "banned",
    "Tamiyo, Inquisitive Student" => "banned",
    "Wrenn and Six" => "banned",
    "Alora, Cheerful Assassin" => "specialized",
    "Alora, Cheerful Mastermind" => "specialized",
    "Alora, Cheerful Scout" => "specialized",
    "Alora, Cheerful Swashbuckler" => "specialized",
    "Alora, Cheerful Thief" => "specialized",
    "Ambergris, Agent of Balance" => "specialized",
    "Ambergris, Agent of Destruction" => "specialized",
    "Ambergris, Agent of Law" => "specialized",
    "Ambergris, Agent of Progress" => "specialized",
    "Ambergris, Agent of Tyranny" => "specialized",
    "Ancestral Recall" => "conjurable",
    "Black Lotus" => "conjurable",
    "Gale, Abyssal Conduit" => "specialized",
    "Gale, Holy Conduit" => "specialized",
    "Gale, Primeval Conduit" => "specialized",
    "Gale, Storm Conduit" => "specialized",
    "Gale, Temporal Conduit" => "specialized",
    "Gut, Bestial Fanatic" => "specialized",
    "Gut, Brutal Fanatic" => "specialized",
    "Gut, Devious Fanatic" => "specialized",
    "Gut, Furious Fanatic" => "specialized",
    "Gut, Zealous Fanatic" => "specialized",
    "Hag of Ceaseless Torment" => "conjurable",
    "Hag of Dark Duress" => "conjurable",
    "Hag of Death's Legion" => "conjurable",
    "Hag of Inner Weakness" => "conjurable",
    "Hag of Mage's Doom" => "conjurable",
    "Hag of Noxious Nightmares" => "conjurable",
    "Hag of Scoured Thoughts" => "conjurable",
    "Hag of Syphoned Breath" => "conjurable",
    "Hag of Twisted Visions" => "conjurable",
    "Imoen, Chaotic Trickster" => "specialized",
    "Imoen, Honorable Trickster" => "specialized",
    "Imoen, Occult Trickster" => "specialized",
    "Imoen, Wily Trickster" => "specialized",
    "Imoen, Wise Trickster" => "specialized",
    "Jaheira, Heroic Harper" => "specialized",
    "Jaheira, Insightful Harper" => "specialized",
    "Jaheira, Merciful Harper" => "specialized",
    "Jaheira, Ruthless Harper" => "specialized",
    "Jaheira, Stirring Harper" => "specialized",
    "Karlach, Tiefling Berserker" => "specialized",
    "Karlach, Tiefling Guardian" => "specialized",
    "Karlach, Tiefling Punisher" => "specialized",
    "Karlach, Tiefling Spellrager" => "specialized",
    "Karlach, Tiefling Zealot" => "specialized",
    "Klement, Death Acolyte" => "specialized",
    "Klement, Knowledge Acolyte" => "specialized",
    "Klement, Life Acolyte" => "specialized",
    "Klement, Nature Acolyte" => "specialized",
    "Klement, Tempest Acolyte" => "specialized",
    "Lae'zel, Blessed Warrior" => "specialized",
    "Lae'zel, Callous Warrior" => "specialized",
    "Lae'zel, Illithid Thrall" => "specialized",
    "Lae'zel, Primal Warrior" => "specialized",
    "Lae'zel, Wrathful Warrior" => "specialized",
    "Lukamina, Bear Form" => "specialized",
    "Lukamina, Crocodile Form" => "specialized",
    "Lukamina, Hawk Form" => "specialized",
    "Lukamina, Scorpion Form" => "specialized",
    "Lukamina, Wolf Form" => "specialized",
    "Lulu, Curious Hollyphant" => "specialized",
    "Lulu, Helpful Hollyphant" => "specialized",
    "Lulu, Inspiring Hollyphant" => "specialized",
    "Lulu, Vengeful Hollyphant" => "specialized",
    "Lulu, Wild Hollyphant" => "specialized",
    "Mox Emerald" => "conjurable",
    "Mox Jet" => "conjurable",
    "Mox Pearl" => "conjurable",
    "Mox Ruby" => "conjurable",
    "Mox Sapphire" => "conjurable",
    "Rasaad, Dragon Monk" => "specialized",
    "Rasaad, Radiant Monk" => "specialized",
    "Rasaad, Shadow Monk" => "specialized",
    "Rasaad, Sylvan Monk" => "specialized",
    "Rasaad, Warrior Monk" => "specialized",
    "Sarevok, Deadly Usurper" => "specialized",
    "Sarevok, Deceitful Usurper" => "specialized",
    "Sarevok, Divine Usurper" => "specialized",
    "Sarevok, Ferocious Usurper" => "specialized",
    "Sarevok, Mighty Usurper" => "specialized",
    "Shadowheart, Cleric of Graves" => "specialized",
    "Shadowheart, Cleric of Order" => "specialized",
    "Shadowheart, Cleric of Trickery" => "specialized",
    "Shadowheart, Cleric of Twilight" => "specialized",
    "Shadowheart, Cleric of War" => "specialized",
    "Skanos, Black Dragon Vassal" => "specialized",
    "Skanos, Blue Dragon Vassal" => "specialized",
    "Skanos, Green Dragon Vassal" => "specialized",
    "Skanos, Red Dragon Vassal" => "specialized",
    "Skanos, White Dragon Vassal" => "specialized",
    "Time Walk" => "conjurable",
    "Timetwister" => "conjurable",
    "Tropical Island" => "conjurable",
    "Vhal, Scholar of Creation" => "specialized",
    "Vhal, Scholar of Elements" => "specialized",
    "Vhal, Scholar of Mortality" => "specialized",
    "Vhal, Scholar of Prophecy" => "specialized",
    "Vhal, Scholar of Tactics" => "specialized",
    "Viconia, Disciple of Arcana" => "specialized",
    "Viconia, Disciple of Blood" => "specialized",
    "Viconia, Disciple of Rebirth" => "specialized",
    "Viconia, Disciple of Strength" => "specialized",
    "Viconia, Disciple of Violence" => "specialized",
    "Wilson, Ardent Bear" => "specialized",
    "Wilson, Fearsome Bear" => "specialized",
    "Wilson, Majestic Bear" => "specialized",
    "Wilson, Subtle Bear" => "specialized",
    "Wilson, Urbane Bear" => "specialized",
    "Wyll of the Blade Pact" => "specialized",
    "Wyll of the Celestial Pact" => "specialized",
    "Wyll of the Elder Pact" => "specialized",
    "Wyll of the Fey Pact" => "specialized",
    "Wyll of the Fiend Pact" => "specialized",
  )
end
