BanList.for_format("mtgo commander") do
  format_start(
    "https://magic.wizards.com/en/articles/archive/magic-online/1v1-commander-banned-list",
    "Amulet of Quoz" => "banned",
    "Ancestral Recall" => "banned",
    "Arcum Dagsson" => "banned",
    "Back to Basics" => "banned",
    "Balance" => "banned",
    "Bazaar of Baghdad" => "banned",
    "Biorhythm" => "banned",
    "Black Lotus" => "banned",
    "Braids, Cabal Minion" => "banned",
    "Bronze Tablet" => "banned",
    "Channel" => "banned",
    "Chaos Orb" => "banned",
    "Contract from Below" => "banned",
    "Darkpact" => "banned",
    "Demonic Attorney" => "banned",
    "Derevi, Empyrial Tactician" => "banned",
    "Doomsday" => "banned",
    "Edric, Spymaster of Trest" => "banned",
    "Entomb" => "banned",
    "Erayo, Soratami Ascendant" => "banned",
    "Erayo's Essence" => "banned",
    "Falling Star" => "banned",
    "Fastbond" => "banned",
    "Food Chain" => "banned",
    "Gaea's Cradle" => "banned",
    "Gifts Ungiven" => "banned",
    "Griselbrand" => "banned",
    "Hermit Druid" => "banned",
    "Humility" => "banned",
    "Jeweled Bird" => "banned",
    "Karakas" => "banned",
    "Library of Alexandria" => "banned",
    "Limited Resources" => "banned",
    "Mana Crypt" => "banned",
    "Mana Drain" => "banned",
    "Mana Vault" => "banned",
    "Mind Twist" => "banned",
    "Mishra's Workshop" => "banned",
    "Moat" => "banned",
    "Mox Emerald" => "banned",
    "Mox Jet" => "banned",
    "Mox Pearl" => "banned",
    "Mox Ruby" => "banned",
    "Mox Sapphire" => "banned",
    "Natural Order" => "banned",
    "Necropotence" => "banned",
    "Oath of Druids" => "banned",
    "Painter's Servant" => "banned",
    "Protean Hulk" => "banned",
    "Rebirth" => "banned",
    "Rofellos, Llanowar Emissary" => "banned",
    "Sensei's Divining Top" => "banned",
    "Serra Ascendant" => "banned",
    "Shahrazad" => "banned",
    "Sol Ring" => "banned",
    "Survival of the Fittest" => "banned",
    "Tempest Efreet" => "banned",
    "The Tabernacle at Pendrell Vale" => "banned",
    "Time Vault" => "banned",
    "Time Walk" => "banned",
    "Timmerian Fiends" => "banned",
    "Tinker" => "banned",
    "Tolarian Academy" => "banned",
    "Trade Secrets" => "banned",
    "Yawgmoth's Bargain" => "banned",
    "Yisan, the Wanderer Bard" => "banned",
    "Zur the Enchanter" => "banned",
  )

  change(
    "2017-05-24",
    "http://wizardsmtgo.tumblr.com/post/161023137579/commander-1v1-banned-update",
    "Dig Through Time" => "banned",
    "Strip Mine" => "banned",
    "Treasure Cruise" => "banned",
  )

  change(
    "2017-07-05",
    "http://wizardsmtgo.tumblr.com/post/162630833904/commander-1v1-banned-update",
    "Brainstorm" => "banned",
    "Ponder" => "banned",
    "Preordain" => "banned",
    "Treachery" => "banned",
    "Vial Smasher the Fierce" => "banned",
    "Biorhythm" => "legal",
    "Limited Resources" => "legal",
    "Painter's Servant" => "legal",
    "Trade Secrets" => "legal",
  )

  change(
    "2017-10-11",
    "http://wizardsmtgo.tumblr.com/post/166220048834/mtgo-commander-1v1-banned-announcement",
    "Baral, Chief of Compliance" => "banned",
    "Demonic Tutor" => "banned",
    "Emrakul, the Aeons Torn" => "banned",
    "Enlightened Tutor" => "banned",
    "Imperial Seal" => "banned",
    "Mystical Tutor" => "banned",
    "Vampiric Tutor" => "banned",
    "Arcum Dagsson" => "legal",
    "Yisan, the Wanderer Bard" => "legal",
  )

  change(
    "2018-04-16",
    "http://wizardsmtgo.tumblr.com/post/172998145739/1v1-commander-banned-and-restricted-announcement",
    "Edgar Markov" => "banned",
    "Chrome Mox" => "banned",
    "Ancient Tomb" => "banned",
    "Mox Diamond" => "banned",
    "Winter Orb" => "banned",
    "Sylvan Library" => "banned",
    "Worldly Tutor" => "banned",
    "Sylvan Tutor" => "banned",
    "Protean Hulk" => "legal",
    "Mishra's Workshop" => "legal",
    "Bazaar of Baghdad" => "legal",
    "Griselbrand" => "legal",
  )

  change(
    "2018-07-25",
    "https://magic.wizards.com/en/articles/archive/magic-online/magic-online-1v1-commander-update-2018-07-20",
    "Ancient Tomb" => "legal",
    "Brainstorm" => "legal",
    "Chrome Mox" => "legal",
    "Demonic Tutor" => "legal",
    "Dig Through Time" => "legal",
    "Enlightened Tutor" => "legal",
    "Entomb" => "legal",
    "Gaea's Cradle" => "legal",
    "Imperial Seal" => "legal",
    "Mana Crypt" => "legal",
    "Mana Drain" => "legal",
    "Mana Vault" => "legal",
    "Mox Diamond" => "legal",
    "Mystical Tutor" => "legal",
    "Necropotence" => "legal",
    "Ponder" => "legal",
    "Preordain" => "legal",
    "Sol Ring" => "legal",
    "Sylvan Tutor" => "legal",
    "Treachery" => "legal",
    "Treasure Cruise" => "legal",
    "Vampiric Tutor" => "legal",
    "Vial Smasher the Fierce" => "legal",
    "Worldly Tutor" => "legal",
    "Yawgmoth's Bargain" => "legal",
  )

  change(
    "2020-06-10",
    "https://magic.wizards.com/en/articles/archive/news/depictions-racism-magic-2020-06-10",
    "Cleanse" => "banned",
    "Crusade" => "banned",
    "Imprison" => "banned",
    "Invoke Prejudice" => "banned",
    "Jihad" => "banned",
    "Pradesh Gypsies" => "banned",
    "Stone-Throwing Devils" => "banned",
  )
end
