class ConditionIsManland < ConditionNickname
  def names
    [
      "blinkmoth nexus",
      "cactus preserve",
      "cave of the frost dragon",
      "cavernous maw",
      "celestial colonnade",
      "creeping tar pit",
      "den of the bugbear",
      "domesticated watercourse",
      "dread statuary",
      "faceless haven",
      "faerie conclave",
      "forbidding watchtower",
      "frostwalk bastion",
      "ghitu encampment",
      "hall of storm giants",
      "hissing quagmire",
      "hive of the eye tyrant",
      "hostile desert",
      "inkmoth nexus",
      "lair of the hydra",
      "lavaclaw reaches",
      "lumbering falls",
      "mishra's factory",
      "mishra's foundry",
      "mobilized district",
      "mutavault",
      "nantuko monastery",
      "needle spires",
      "raging ravine",
      "restless anchorage",
      "restless bivouac",
      "restless cottage",
      "restless fortress",
      "restless prairie",
      "restless reef",
      "restless ridgeline",
      "restless spire",
      "restless vents",
      "restless vinestalk",
      "shambling vent",
      "soulstone sanctuary",
      "spawning pool",
      "stalking stones",
      "stirring wildwood",
      "svogthos, the restless tomb",
      "the magical city, new",
      "treetop village",
      "urza's hot dog stand",
      "wandering fumarole",
    ]
  end

  def to_s
    "is:manland"
  end
end
