class ConditionIsAttraction < ConditionNickname
  def names
    [
      # https://magic.wizards.com/en/news/announcements/may-13-2024-banned-and-restricted-announcement
      "coming attraction",
      "complaints clerk",
      "deadbeat attendant",
      "dee kay, finder of the lost",
      "discourtesy clerk",
      "draconian gate-bot",
      "\"lifetime\" pass holder",
      "line cutter",
      "monitor monitor",
      "myra the magnificent",
      "petting zookeeper",
      "quick fixer",
      "rad rascal",
      "ride guide",
      "seasoned buttoneer",
      "soul swindler",
      "spinnerette, arachnobat",
      "squirrel squatters",
      "step right up",
      "the most dangerous gamer",
      # t:attraction
      "balloon stand",
      "bounce chamber",
      "bumper cars",
      "centrifuge",
      "clown extruder",
      "concession stand",
      "costume shop",
      "cover the spot",
      "dart throw",
      "drop tower",
      "ferris wheel",
      "foam weapons kiosk",
      "fortune teller",
      "gallery of legends",
      "gift shop",
      "guess your fate",
      "hall of mirrors",
      "haunted house",
      "information booth",
      "kiddie coaster",
      "log flume",
      "memory test",
      "merry-go-round",
      "pick-a-beeble",
      "push your luck",
      "roller coaster",
      "scavenger hunt (a)",
      "scavenger hunt (b)",
      "scavenger hunt (c)",
      "scavenger hunt (d)",
      "scavenger hunt (e)",
      "scavenger hunt (f)",
      "spinny ride",
      "squirrel stack",
      "storybook ride",
      "swinging ship",
      "the superlatorium (a)",
      "the superlatorium (b)",
      "the superlatorium (c)",
      "the superlatorium (d)",
      "the superlatorium (e)",
      "the superlatorium (f)",
      "trash bin",
      "trivia contest (a)",
      "trivia contest (b)",
      "trivia contest (c)",
      "trivia contest (d)",
      "trivia contest (e)",
      "trivia contest (f)",
      "tunnel of love",
      # on both stickers list and attraction list
      "command performance",
      # acorn
      "goblin blastronauts"
    ]
  end

  def to_s
    "is:attraction"
  end
end
