source "https://rubygems.org"

ruby ">= 2.7"

# Bundle edge Rails instead: gem "rails", github: "rails/rails"
gem "rails", "~> 6.1.7.10"
# Use SCSS for stylesheets
gem "sass-rails"
# Use Terser as compressor for JavaScript assets
gem "terser"
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem "therubyracer", platforms: :ruby

# Use jquery as the JavaScript library
gem "jquery-rails"
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem "turbolinks"

gem "bootstrap", "~> 4.3.1"
gem "select2-rails"
gem "net-smtp", require: false # Ruby 3.1 issue

gem "concurrent-ruby", "1.3.4" # 1.3.5 has some dependency issues
gem "ffi", "1.16.3" # 1.17 only ships native gems for Ruby 3.0+

# Ruby 3.4 demoted these from default gems to bundled gems, so they're no longer
# on the load path of a bundled app, but Rails 6.1 still requires them implicitly.
# Must stay conditional: from 2.7 through 3.2 they are still default gems that load
# on their own, so naming them here would only add versions we never asked for to
# the lockfile.
#
# Ruby 3.3 doesn't need any of them, but still warns
if RUBY_VERSION >= "3.3"
  gem "mutex_m"
  gem "drb"
  gem "base64"
  gem "bigdecimal"
  gem "observer"
  gem "abbrev"
  gem "benchmark" # not a default gem from Ruby 4.0, warns under 3.4
  gem "csv" # DeckParser reads the CSV export back
end

# Use ActiveModel has_secure_password
# gem "bcrypt", "~> 3.1.7"

# Use Unicorn as the app server
# gem "unicorn"

gem "haml"
gem "will_paginate"
gem "damerau-levenshtein"
gem "famfamfam_flags_rails"
gem "nokogiri"

# It doesn't work with 4.0
gem "sprockets", "3.7.2"

group :development, :test do
  # Call "byebug" anywhere in the code to stop execution and get a debugger console
  gem "byebug"
  gem "pry"
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem "web-console"

  gem "listen"
  gem "pathname-glob"
end

group :test do
  gem "rspec-rails"
end

group :production do
  gem "puma", "< 5" # 5+ has different demon calls
end
