class FormatModern < Format
  def format_pretty_name
    "Modern"
  end

  # Modern debuted as an unsanctioned Magic Online format at the 2011 Community Cup,
  # this is the announcement which turned it into a real format and published its initial ban list.
  # (Magic Online support followed on 2011-08-24, first sanctioned event was Pro Tour Philadelphia.)
  # https://magic.wizards.com/en/articles/archive/latest-developments/welcome-modern-world-2011-08-12
  def format_start_date
    "2011-08-12"
  end

  def build_included_sets
    Set[
      "8ed",
      "mrd", "dst", "5dn",
      "chk", "bok", "sok",
      "9ed",
      "rav", "gpt", "dis",
      "csp",
      "tsp", "tsb", "plc", "fut",
      "10e",
      "lrw", "mor", "shm", "eve",
      "ala", "con", "arb",
      "m10",
      "zen", "wwk", "roe",
      "m11",
      "som", "mbs", "nph",
      "m12",
      "isd", "dka", "avr",
      "m13",
      "rtr", "gtc", "dgm",
      "m14",
      "ths", "bng", "jou",
      "m15",
      "ktk", "frf", "dtk",
      "ori",
      "bfz", "ogw",
      "soi", "w16", "emn",
      "kld", "aer",
      "akh", "w17", "hou",
      "xln", "rix",
      "dom",
      "m19", "g18",
      "grn", "rna", "war",
      "mh1",
      "m20",
      "eld",
      "thb",
      "iko",
      "m21",
      "znr",
      "khm",
      "stx",
      "mh2",
      "afr",
      "mid",
      "vow",
      "neo",
      "snc",
      "dmu",
      "bro",
      "one",
      "mom",
      "mat",
      "ltr",
      "woe",
      "lci",
      "mkm",
      "otj",
      "big",
      "h2r",
      "mh3",
      "acr",
      "blb",
      "dsk",
      "fdn",
      "dft",
      "tdm",
      "fin",
      "eoe",
      "spm",
      "tla",
      "ecl",
      "tmt",
      "sos",
      "msh",
    ]
  end
end
