class FormatModern < Format
  def format_pretty_name
    "Modern"
  end

  def build_included_sets
    Set[
      "8ed",
      "mrd", "dst", "5dn",
      "chk", "bok", "sok",
      "9ed",
      "rav", "gpt", "dis",
      "csp",
      "tsp", "tsb", "plc", "fut",
      "10e",
      "lrw", "mor", "shm", "eve",
      "ala", "con", "arb",
      "m10",
      "zen", "wwk", "roe",
      "m11",
      "som", "mbs", "nph",
      "m12",
      "isd", "dka", "avr",
      "m13",
      "rtr", "gtc", "dgm",
      "m14",
      "ths", "bng", "jou",
      "m15",
      "ktk", "frf", "dtk",
      "ori",
      "bfz", "ogw",
      "soi", "w16", "emn",
      "kld", "aer",
      "akh", "w17", "hou",
      "xln", "rix",
      "dom",
      "m19", "g18",
      "grn", "rna", "war",
      "mh1",
      "m20",
      "eld",
      "thb",
      "iko",
      "m21",
      "znr",
      "khm",
      "stx",
      "mh2",
      "afr",
      "mid",
      "vow",
      "neo",
      "snc",
      "dmu",
      "bro",
      "one",
      "mom",
      "mat",
      "ltr",
    ]
  end
end
