# Some are ability words, some are flavor words from various sets
# At this point there's too many to bother with the distinction
module AbilityWord
  ABILITY_WORD_LIST = [
    "A Murder at Markov Manor",
    "A Thousand Souls Die Every Day",
    "Aberrant Tinkering",
    "Abraxas",
    "Acid Breath",
    "Adamant",
    "Addendum",
    "Advanced Species",
    "Advertising",
    "Aegis of the Emperor",
    "Aerial Blast",
    "Aerospark",
    "Affirmative",
    "Alliance",
    "Allies",
    "Allure of Slaanesh",
    "Alluring Eyes",
    "Angelo Cannon",
    "Animate Chains",
    "Animate Walking Statue",
    "Ansur's Sanctum",
    "Architect of Deception",
    "Archives",
    "Arena",
    "Armour of Shrieking Souls",
    "Astral Projection",
    "Atomic Transmutation",
    "Auntie's Teahouse",
    "Avian Telepathy",
    "Avoidance",
    "Bad Breath",
    "Bad Wolf",
    "Balthazar's Lab",
    "Battalion",
    "Battle Cannon",
    "Beacon of Hope",
    "Bear Form",
    "Bear Witness",
    "Benediction of the Omnissiah",
    "Berserk",
    "Berzerker",
    "Betrayal",
    "Bewitching Whispers",
    "Bigby's Hand",
    "Binding Contract",
    "Blade of Magnus",
    "Blessing of Light",
    "Blind Betrayal",
    "Blitzball Captain",
    "Blood Chalice",
    "Blood Drain",
    "Bloodrush",
    "Blow Up",
    "Blue Magic",
    "Body Thief",
    "Brave Heart",
    "Brimstone",
    "Brontosaurus",
    "Brood Telepathy",
    "Burning Chains",
    "Byzantium Radiation",
    "Calim's Breath",
    "Camouflage",
    "Catacombs",
    "Cave Entrance",
    "Ceaseless Tempest",
    "Celebration",
    "Ceremorphosis",
    "Chain",
    "Chainsword",
    "Channel",
    "Channelstorm",
    "Chaos Control",
    "Chaos",
    "Chaosbringer",
    "Chapter Master",
    "Cheer",
    "Chef's Knife",
    "Children of the Cult",
    "Chroma",
    "Circle of Death",
    "Circus of the Last Days",
    "Climb Over",
    "Cohort",
    "Cold Breath",
    "Cold Snap",
    "Combat Inspiration",
    "Come Fly With Me",
    "Command Protocols",
    "Command Section",
    "Concealed Position",
    "Cone of Cold",
    "Confounding Clouds",
    "Conjure Elemental",
    "Constellation",
    "Consume Anomaly",
    "Converge",
    "Corrupted Metalcraft",
    "Corrupted",
    "Coruscating Flames",
    "Cosmic Awareness",
    "Cosmo Memory",
    "Council's dilemma",
    "Coven",
    "Covercast",
    "Cradle of the Death God",
    "Crash Landing",
    "Create Undead",
    "Crescent Fang",
    "Crown of Madness",
    "Crushing Teeth",
    "Cunning Action",
    "Curse of the Walking Pox",
    "Cybernetic Senses",
    "Daemon Sword",
    "Dance",
    "Dark One's Own Luck",
    "Dark Pool",
    "Darkforce Inversion",
    "Darkness",
    "Deal with the Black Guardian",
    "Death Frenzy",
    "Death Sickle",
    "Decimate",
    "Deep Mines",
    "Defiled Temple",
    "Delirium",
    "Designed Only for Killing",
    "Devastating Charge",
    "Devour Intellect",
    "Devourer of Souls",
    "Devouring Monster",
    "Diamond Dust",
    "Diana",
    "Dinosaur Formula",
    "Disappear",
    "Displacement",
    "Dissolve",
    "Distract the Horde",
    "Divine Intervention",
    "Domain",
    "Dominate Monster",
    "Double Overdrive",
    "Double",
    "Drag Below",
    "Dragonfire Dive",
    "Drain Life",
    "Draw Arcanum",
    "Dualcast",
    "Dungeon Level",
    "Dynastic Advisor",
    "Dynastic Codes",
    "Dynastic Command Node",
    "Each opponent faces a villainous choice",
    "Ebonlake Grotto",
    "Echo of the First Murder",
    "Echo of the Lost",
    "Ecliptic Growl",
    "Eerie",
    "Elite Troops",
    "Embiggen Fist",
    "Emerald Grove",
    "Eminence",
    "Endless Swarm",
    "Endurant",
    "Engulf",
    "Enmitic Exterminator",
    "Enrage",
    "Enthralling Performance",
    "Establishing Shot",
    "Eternity Gate",
    "Eukrasia",
    "Everypony's Invited",
    "Exhaust",
    "Exile Cannon",
    "Fabricator Claw Array",
    "Fall",
    "Fallen Warrior",
    "Family Gathering",
    "Fast Healing",
    "Fateful Bite",
    "Fateful hour",
    "Fathomless descent",
    "Fear Gas",
    "Federation",
    "Feeder Mandibles",
    "Ferocious",
    "Field Reprogramming",
    "Find New Host",
    "Fire Breath",
    "Fire Cross",
    "Fire of Tzeentch",
    "Fire",
    "First Contact",
    "Fixed commander ninjutsu",
    "Flames of Rebirth",
    "Flare Star",
    "Flesh Flayer",
    "Flesh Hooks",
    "Flurry of Blows",
    "Flurry",
    "Focus Beam",
    "For Auld Lang Syne",
    "Forge",
    "Formidable",
    "Frenzied Metabolism",
    "Frenzied Rampage",
    "From Downtown",
    "From the Future",
    "Full Party",
    "Fungi Cavern",
    "Gae Bolg",
    "Gathered Swarm",
    "Gatling Blaster",
    "Gauntlet of Shar",
    "Genestealer's Kiss",
    "Genius Industrialist",
    "Genomic Enhancement",
    "Gestalt Mode",
    "Gift of Chaos",
    "Gift of Tiamat",
    "Gigaflare",
    "Glory of Battle",
    "Goblin Bazaar",
    "Goblin Camp",
    "Goblin Formula",
    "Goblin Lair",
    "Golden Rule",
    "Gotcha",
    "Gotta Go Fast",
    "Grand Strategist",
    "Grand Summon",
    "Grandeur",
    "Grant an Advantage",
    "Grymforge",
    "Guardian Protocols",
    "Gungnir",
    "Gust of Wind",
    "Hagneia",
    "Hall of Sorrow",
    "Harbinger of Despair",
    "Healing Tears",
    "Heavenly Strike",
    "Heavenward Howl",
    "Heavy Power Hammer",
    "Heavy Rock Cutter",
    "Hellbent",
    "Hero's Reward",
    "Hero's Sundering",
    "Heroic",
    "History Teacher",
    "Hive Mind",
    "Homunculus Servant",
    "Horrific Symbiosis",
    "How Civil of You",
    "Hunt for Heresy",
    "Hunters for Hire",
    "Hyperphase Threshers",
    "Hypertoxic Miasma",
    "I Denial",
    "Ice",
    "II Anger",
    "III Bargaining",
    "Immune",
    "Impossible Girl",
    "Imprint",
    "Infesting Spores",
    "Infusion",
    "Inquisition Agents",
    "Insatiable Hunger",
    "Inspired",
    "Intangibility",
    "Into the TARDIS",
    "Invasion Beams",
    "Invoke Duplicity",
    "IV Depression",
    "Jecht Beam",
    "Jenova Cells",
    "Join forces",
    "Jolly Gutpipes",
    "Judgment Bolt",
    "Jump",
    "Keen Senses",
    "Keen Sight",
    "Kerplunk",
    "Kinfall",
    "Kinship",
    "Krishna",
    "Landerfall",
    "Landfall",
    "Landship",
    "Last Light Inn",
    "Leading from the Front",
    "Leap of Faith",
    "Leap Strike",
    "Legacy",
    "Lethal Voice",
    "Lieutenant",
    "Life Drain",
    "Light Party",
    "Lightbringer and Hero's Shield",
    "Lightning Breath",
    "Lightning",
    "Lizard Formula",
    "Locus of Slaanesh",
    "Look to the Stars",
    "Lord of Chaos",
    "Lord of the Pyrrhian Legions",
    "Lord of Torment",
    "Lost Level",
    "Lost Well",
    "Loud Ruckus",
    "Low Gravity",
    "Lucky Slots",
    "Lunge",
    "Lure the Unwary",
    "Machina",
    "Mad Wizard's Lair",
    "Mage Hand",
    "Magecraft",
    "Magical Tinkering",
    "Make Them Pay",
    "Mama's Coming",
    "Mantle of Inspiration",
    "Mark of Chaos Ascendant",
    "Martyrdom",
    "Master of Machines",
    "Master Tactician",
    "Matter Absorption",
    "Max Speed",
    "Medicus Ministorum",
    "Meet in Reverse",
    "Mega Flare",
    "Mental Organism",
    "Mesmerize",
    "Metalcraft",
    "Midnight Entity",
    "Mind Swap",
    "Mine Tunnels",
    "Mine Vibranium",
    "Mirran Victory",
    "Mold Earth",
    "Mold Harvest",
    "Molting Exoskeleton",
    "Mono Eminence",
    "Moonrise Towers",
    "Morbid",
    "Mountain Pass",
    "Mug",
    "Muiral's Graveyard",
    "Murasame",
    "Mutsunokami",
    "My First Friend",
    "My Will Be Done",
    "Mystic Arcanum",
    "Natural Recovery",
    "Natural Shelter",
    "Negative Energy Cone",
    "Negative",
    "Neurotraumal Rod",
    "No Mercy",
    "Nosh",
    "Oblivion",
    "Old Companion",
    "One for My Baby",
    "Opus",
    "Oubliette",
    "Pack tactics",
    "Pact Boon",
    "Pain",
    "Paradox",
    "Parallel Universe",
    "Parley",
    "Particle Beam",
    "Peaceful Coexistence",
    "Perfect Illumination",
    "Perseus's Bow",
    "Phaeron",
    "Phalanx Commander",
    "Pheromone Trail",
    "Photographic Reflexes",
    "Phyrexian Victory",
    "Plasma Incinerator",
    "Play Arcanum",
    "Poison Breath",
    "Polymorphine",
    "Praesidium Protectiva",
    "Praise Him",
    "Pray",
    "Primarch of the Death Guard",
    "Prince of Chaos",
    "Prismatic Gallery",
    "Probing Telepathy",
    "Proclamator Hailer",
    "Project Image",
    "Protect",
    "Protection Fighting Style",
    "Protector",
    "Psionic Adept",
    "Psionic Spells",
    "Psychic Abomination",
    "Psychic Blades",
    "Psychic Defense",
    "Psychic Stimulus",
    "Radar Sense",
    "Radiance",
    "Rage Beyond Death",
    "Rage",
    "Raid",
    "Raise",
    "Rally",
    "Rapacious Hunger",
    "Rapid Regeneration",
    "Rappel Down",
    "Rat Tail",
    "Reckless Behavior",
    "Reithwin Tollhouse",
    "Rejuvenation",
    "Relentless March",
    "Renew",
    "Repair Barge",
    "Repartee",
    "Requirement",
    "Reverberating Summons",
    "Revolt",
    "Reward",
    "Rising Flames",
    "Rites of Banishment",
    "Rogue Trader",
    "Ronso Rage",
    "Rope Dart",
    "Rosarius",
    "Rot Fly",
    "Rough Divide",
    "Royal Guard",
    "Ruinous Ascension",
    "Rule Zero",
    "Rulebreaker",
    "Runestone Caverns",
    "Sage Project",
    "Sanctified Rules of Combat",
    "Sandfall Cell",
    "Sarcophagus",
    "Scavenge the Dead",
    "Science Teacher",
    "Scions' Secretary",
    "Scorching Ray",
    "Scryfall",
    "Search the Room",
    "Secret council",
    "Secret Entrance",
    "Secrets of the Soul",
    "Seismic Takedown",
    "Selfie Shot",
    "Sensational Save",
    "Sense the Good",
    "Share Intelligence",
    "Share",
    "Shieldwall",
    "Shiva's Aid",
    "Shooting Star",
    "Show",
    "Shrieking Gargoyles",
    "Siege Monster",
    "Sigil of Corruption",
    "Sketch and Lore",
    "Skilled Outrider",
    "Skyswarm",
    "Sleight of Hand",
    "Slipstream",
    "Smear Campaign",
    "Sneak Attack",
    "Sokratic Dialogue",
    "Song of the Ood",
    "Sonic Attack",
    "Sonic Blast",
    "Sonic Blaster",
    "Sonic Booster",
    "Sonic Rainboom",
    "Sonic Wings",
    "Sorcerous Elixir",
    "Sorcerous Inspiration",
    "Spawn Termagants",
    "Spear of the Void Dragon",
    "Spell mastery",
    "Spiked Retribution",
    "Spirit of the Whalaqee",
    "Spiritual Leader",
    "Split",
    "Spoilers",
    "Spore Chimney",
    "Spring",
    "Stagger",
    "Starfall",
    "Starscourge",
    "Stash",
    "Steal",
    "Steel Watch Foundry",
    "Still Point in Time",
    "Storeroom",
    "Stowage",
    "Strategic Coordinator",
    "Strive",
    "Stunning Strike",
    "Subterranean Assault",
    "Summary Execution",
    "Summer",
    "Summon",
    "Super Nova",
    "Suppressing Fire",
    "Survey the Realm",
    "Survival",
    "Suspended Animation",
    "Sweep",
    "Symphony of Pain",
    "Synapse Creature",
    "Synaptic Disintegrator",
    "Tail Spikes",
    "Targeting Relay",
    "Team Cloudspire",
    "Team Speed Demons",
    "Team TARDIS",
    "Teamwork",
    "Teleport",
    "Temple of Bhaal",
    "Temple of Dumathoin",
    "Temporal Foresight",
    "Tempting offer",
    "Tempting Offer",
    "Terror from the Deep",
    "The Allagan Eye",
    "The Betrayer",
    "The Last Centurion",
    "The Minstrel's Ballad",
    "The Most Important Punch in History",
    "The Reunion",
    "The Will of the Hive Mind",
    "Those Who Came Before",
    "Three Autostubs",
    "Threshold",
    "Throne of the Dead Three",
    "Throw Wide the Gates",
    "Throw",
    "Tie Up",
    "Time Compression",
    "Time Lord's Prerogative",
    "Titanic",
    "Tools",
    "Top of the Food Chain",
    "Toxic Spores",
    "Trace Aether",
    "Trade Routes",
    "Tragic Backstory",
    "Trance",
    "Transdimensional Scout",
    "Translocation Protocols",
    "Trapped Entry",
    "Treasure Hunter",
    "Trick Arrows",
    "Triple",
    "Twisted Caverns",
    "Tyrannosaurus Rex",
    "Ultima Founding",
    "Ultimate End",
    "Ultimate Jecht Shot",
    "Ultimate Sacrifice",
    "Unbreakable Skin",
    "Undercity Ruins",
    "Underdog",
    "Undergrowth",
    "Undying Vengeance",
    "Unearthly Power",
    "Unlock Ability",
    "Unquestionable Wisdom",
    "Unreliable Visions",
    "Unrivaled Lethality",
    "V Acceptance",
    "Valiant",
    "Vanguard Species",
    "Veil of Time",
    "Veils of Fear",
    "Venom Blast",
    "Vicious Mockery",
    "Vivid",
    "Void Shields",
    "Void",
    "Wark",
    "Warp Blast",
    "Warp Vortex",
    "Wasp's Sting",
    "Water Always Wins",
    "Wave Cannon",
    "Web Support",
    "Weird Insight",
    "Whirlwind",
    "Whispers of the Grave",
    "Wild Card",
    "Wild Magic Surge",
    "Wild Shape",
    "Will of the council",
    "Will of the Planeswalkers",
    "Wind Walk",
    "Wings of Light",
    "Winter",
    "Woman Who Walked the Earth",
    "Wraith Form",
    "Xenos Cunning",
    "Yawning Portal",
    "You can never leave",
    "Zantetsuken",
  ].sort

  ABILITY_WORD_RX = %r[(?<=^|— )(#{Regexp.union(ABILITY_WORD_LIST)}) —]i
end
