source "https://rubygems.org"
ruby ">= 2.6"
gem "rake"
gem "damerau-levenshtein"
gem "nokogiri"
gem "pry"
gem "rspec", require: false, group: :test
gem "simplecov", require: false, group: :test
gem "pathname-glob"
gem "memory_profiler", require: false, group: :test
gem "fastimage"
gem "calc"
gem "optimist"

# Demoted from default to bundled gem in Ruby 3.4, so it's no longer on the load
# path under bundler. Conditional for the same reason as in frontend/Gemfile.
#
# on 3.3 this isn't necessary, but it generates warning about future upgardes
gem "csv" if RUBY_VERSION >= "3.3"
